name: Release

on:
    push:
        branches:
            - '**'

jobs:
    create_release:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Verify commit message
              id: check_commit
              run: echo "::set-output name=contains_release::$(if git log --format=%B -n 1 $GITHUB_SHA | grep -iq 'release'; then echo true; else echo false; fi)"

            - name: Create release
              id: create_release
              if: steps.check_commit.outputs.contains_release == 'true'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --global user.email "actions@github.com"
                git config --global user.name "GitHub Actions"
                TAG=$(date +'%Y%m%d%H%M%S')
                git tag $TAG $GITHUB_SHA
                git push origin $TAG

                # Create a release
                RELEASE_BODY="Auto-generated release tag $TAG"
                echo "::set-env name=RELEASE_TAG::$TAG"
                echo "::set-env name=RELEASE_BODY::$RELEASE_BODY"

            - name: Publish release
              if: steps.check_commit.outputs.contains_release == 'true'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                echo "Creating release $RELEASE_TAG"
                echo "$RELEASE_BODY" | gh release create $RELEASE_TAG -F -