name: Static Analysis

on:
  pull_request:
    branches:
      - '**'

jobs:
    static-analysis:
      runs-on: macos-latest

      steps: 
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.9'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pylint

        - name: Run static analysis
          run: |
              pylint src/calculator.py
          