name: Static Analysis

on: 
    pull_request:
        branches:
            - '**'

jobs:
    static-analysis:
        runs-on: macos-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4