name: Testing and Building with PyBuilder

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PyBuilder
        run: |
          python -m pip install 'pybuilder>=0.12.0'

      - name: Set PYB_EXTRA_ARGS
        run: |
          echo "PYB_EXTRA_ARGS=upload" >> $GITHUB_ENV

      - name: Execute PyBuilder
        run: |
          pyb -X ${{ env.PYB_EXTRA_ARGS }}
