name: Testing with PyBuilder

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python and PyBuilder
        uses: pybuilder/build@master

      - name: Run PyBuilder build
        run: pyb install_dependencies publish  # Adjust commands as per your project

