name: Testing and Building with PyBuilder

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version:
          - "3.9"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set PyB_EXTRA_ARGS
        run: |
          echo "PYB_EXTRA_ARGS=upload" >> $GITHUB_ENV

      - name: Run PyBuilder with custom args
        uses: pybuilder/build@master
        with:
          python-version: ${{ matrix.python-version }}
          pyb-extra-args: ${{ env.PYB_EXTRA_ARGS }}
          pyb-version: ">=0.13.0.dev0"
